### PR TITLE
Fixed types

### PR DESCRIPTION
**Pull request by ericabrody**
Line 245 added *` to show the multiplication symbol
Line 246 added *` to show the exponential symbol
Line 342 and Line 345 removed \
Line 343 removed 2 \
Line 349, Line 355 removed more \

### CODE REVIEW

**Comment by eah13** [comment]
Nice!  The old `\*` were from when the book was in LaTeX - it's now in Markdown, so these were old bugs

**Comment by eah13** [comment]
@ericabrody wait about an hour and you should see your changes show up in this PDF: http://do1.dr-chuck.com/pythonlearn/EN_us/pythonlearn.pdf  I'll need to rebuild my pages manually when I get a sec to merge in all the other recent changes to this repo

**Comment by ericabrody** [comment]
cool

**Comment by eah13** [comment]
@ericabrody Oh and I almost forgot your celebratory emoji: :boar: :octocat: :boom: :)

**Comment by eah13** [comment]
!! Fixed
screenshot 2016-01-17 at 2 14 46 pm
Very exciting

**Comment by csev** [comment]
Thanks for the patch @ericabrody !

**Pull request merged**
