### PR TITLE
website update

### PR DESCRIPTION
**Pull request by thewhowhatwhere**
site should now be responsive / mobile friendly

### CODE REVIEW

**Comment by eah13** [comment]
+1 nice!  Foundation rocks.

What version is it?  I might suggest pulling from a CDN instead so that the version is explicit (and to make updates easier).  We're not doing any fancy scss stuff so I don't believe we gain a lot by including the source in the repo.

I clicked through the pages and they all looked good on multiple screen sizes.  The HTML in `/book` is still vanilla.  Next step might be getting the headers and nav into `book/index.html` but that can be part of a larger project of getting the HTML version of the book built.

**Comment by thewhowhatwhere** [comment]
Foundation 6.
I was originally pulling from a cdn, however there are a few downsides to doing that.
The biggest being that foreign countries can and will block cdns when or if they feel like it.
Because this is an open course and viewed by people in other countries, I didn't want to take the chance in the site breaking for someone.
There are also security, multipoint failure, and various other issues with using them.

They are great though, and I'm not against using them if that seems like a better idea (saving server bandwidth)

My plan was to remove anything in the assets that wasn't being used and condense them into a single file for fewer http requests. Didn't have time to do it just yet.

**Comment by eah13** [comment]
Ah, I didn't think of the countries blocking CDNs issue.  Makes sense.

**Comment by csev** [comment]
I have an unlimited hosting with 1and1 and a professional CloudFlare account - if these assets become an issue, I will serve them through CloudFlare.   I don't know about other CDNs but with 250K students in my Coursera course in every country in the world and the assignments are all in CloudFlare - it does appear the CloudFlare has 100% coverage.   The issue with some CDNs is https and older browsers - but if you get the CloudFlare pro account - they do perfect https and http on all browsers everywhere as best my Coursera experience shows

**Comment by csev** [comment]
This is now in production - so if it breaks we get to fix it :)

**Comment by thewhowhatwhere** [comment]
awesome!

**Pull request merged**
